development:
  adapter: mysql
  encoding: utf8
  database: Tempo_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: Tempo_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: Tempo
  username: root
  password: 
  host: localhost
